---
- name: combine grafana_kiosk configuration
  set_fact:
    grafana_kiosk: "{{ _grafana_kiosk|combine(grafana_kiosk, recursive=True) }}"

- include_tasks: versioncheck.yml
  when: submodules_versioncheck | bool

- include_tasks: packages.yml
  when: grafana_kiosk.install_requirements | bool

- include_tasks: install.yml

- include_tasks: config.yml

- include_tasks: lightdm.yml
  when: grafana_kiosk.lightdm_autologin | bool
