---
- name: systemctl restart grafana-kiosk.service
  become: true
  systemd:
    state: restarted
    name: grafana-kiosk.service
    daemon_reload: yes
    enabled: true
  when: grafana_kiosk.manage_systemd | bool
